spring.application.name=AttendanceMng

#database
spring.datasource.url=jdbc:MySQL://Localhost:3306/attendancemng?create Database if not exist = true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#for future (student with profile)
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB